---
title: A blog about me
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A blog about software development, electronical awesome things and hobbies
username: Ali Aşkın
user_description: Due to my curiousity about computer technologies and electronics,
  I am trying to learn various fields about technology. Therefore I am willing to
  learn and go further as much as I do.
user_title: Software Developer
email: aliaskin@outlook.com
twitter_username: rpdmania
github_username: darkrpd
linkedin_username: aliaskin
stackoverflow_username: 5244355/rpd
google-analytics:
  id: ''
user_tech_design_description: On the projects I am included, I work with current front
  end techs like famous frameworks,languages and libraries.
user_tech_code_description: My coding experience is the best thing I have. Though
  I work as a Full Stack, I especially love backend technologies.
user_tech_tools_description: Tools are very helpful, also important for the time needed
  on projects. I learn much more tools that help on this road.
exclude:
- package.json
- src
- node_modules
