---
title: Darkrpd.Github.Io
timezone: Asia/Kuwait
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Ali Aşkın
description: Software Developer
avatar: https://avatars3.githubusercontent.com/u/5677816?v=3&u=090ab5f1517f2ae4a10d109410b12b61ea2cd69d&s=400
footer-links:
  dribbble: 
  email: aliaskin@outlook.com
  facebook: 
  flickr: 
  github: darkrpd/
  instagram: 
  linkedin: aliaskin
  pinterest: 
  rss: feed
  twitter: rpdmania
  stackoverflow: users/5244355/rpd
  youtube: 
  googleplus: 
disqus: 
google_analytics: UA-91014408-1
url: http://darkrpd.github.io
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-admin
exclude:
- LICENSE
- README.md
- CNAME
